for(i=1;i<=3;i++)
{
if(i==1){
d3.select("body")
.append("div")
.html("Hi,大家好！学语言真有趣。")
.style('color','yellow')
.style('font-size','x-small');
}
if(i==2){
d3.select("body")
.append("div")
.html("Hi,大家好！学语言真有趣。")
.style('color','blue')
.style('font-size','middle');
}
if(i==3){
d3.select("body")
.append("div")
.html("Hi,大家好！学语言真有趣。")
.style('color','red')
.style('font-size','x-large');
}
}